version: '3'
services:
   ecommerce:
      container_name: ecommerce
      build:
          context: docker-ecommerce
          dockerfile: Dockerfile
      image: ecommerce:latest
      ports:
          - 8080:8080
      networks: 
          - ecommerce-network
        
networks:
  ecommerce-network: